<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class StudentsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('students')->insert([
            [
                'id_student' => 1,
                'name' => 'Andre',
                'birthdate' => '2019-06-19',
                'parent_id' => 4,
                'created_at' => Carbon::parse('2024-10-31 20:39:21'),
                'updated_at' => Carbon::parse('2024-10-31 20:39:21'),
                'id_class' => 1,
            ],
            [
                'id_student' => 2,
                'name' => 'Fernando',
                'birthdate' => '2008-06-25',
                'parent_id' => 4,
                'created_at' => Carbon::parse('2024-10-31 20:54:07'),
                'updated_at' => Carbon::parse('2024-10-31 21:48:36'),
                'id_class' => 1,
            ],
            [
                'id_student' => 4,
                'name' => 'Diego',
                'birthdate' => '2008-06-25',
                'parent_id' => 4,
                'created_at' => Carbon::parse('2024-12-10 17:22:01'),
                'updated_at' => Carbon::parse('2024-12-10 17:22:01'),
                'id_class' => 2,
            ],
            [
                'id_student' => 5,
                'name' => 'João',
                'birthdate' => '2005-07-15',
                'parent_id' => 4,
                'created_at' => Carbon::parse('2024-12-10 17:23:39'),
                'updated_at' => Carbon::parse('2024-12-10 17:23:39'),
                'id_class' => 3,
            ],
            [
                'id_student' => 6,
                'name' => 'Juvenal Cabeção de Melo',
                'birthdate' => '2013-04-12',
                'parent_id' => 3,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 1,
            ],
            [
                'id_student' => 7,
                'name' => 'Gabigol Henrique Arrascaeta',
                'birthdate' => '2013-02-05',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 1,
            ],
            [
                'id_student' => 8,
                'name' => 'Pérola Fofoca de Sousa',
                'birthdate' => '2013-10-30',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 1,
            ],
            [
                'id_student' => 9,
                'name' => 'Zeca Pipoca Farofa',
                'birthdate' => '2013-08-14',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 1,
            ],
            [
                'id_student' => 10,
                'name' => 'Lorde Batatinha Engomado',
                'birthdate' => '2021-01-01',
                'parent_id' => 3,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 1,
            ],
            [
                'id_student' => 11,
                'name' => 'Mini Vegetti Sofredor',
                'birthdate' => '1924-12-25',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 1,
            ],
            [
                'id_student' => 12,
                'name' => 'Gatolino Nerdowski',
                'birthdate' => '2019-04-01',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 2,
            ],
            [
                'id_student' => 13,
                'name' => 'Gatolino Descoladovski',
                'birthdate' => '2020-06-20',
                'parent_id' => 2,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 2,
            ],
            [
                'id_student' => 14,
                'name' => 'Creuzolina Pipoca Soares',
                'birthdate' => '2013-03-27',
                'parent_id' => 2,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 2,
            ],
            [
                'id_student' => 15,
                'name' => 'Zorildo Rabanada Oliveira',
                'birthdate' => '2012-09-19',
                'parent_id' => 2,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 2,
            ],
            [
                'id_student' => 16,
                'name' => 'Florisbela Marmota de Souza',
                'birthdate' => '2013-05-14',
                'parent_id' => 2,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 2,
            ],
            [
                'id_student' => 17,
                'name' => 'Pafúncio Goiabada dos Santos',
                'birthdate' => '2013-02-10',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 2,
            ],
            [
                'id_student' => 18,
                'name' => 'Barbudo Mirim da Silva',
                'birthdate' => '2012-07-15',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 3,
            ],
            [
                'id_student' => 19,
                'name' => 'JC Retrô Gonzales',
                'birthdate' => '2013-03-03',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 3,
            ],
            [
                'id_student' => 20,
                'name' => 'Totó Orelhudo Leãozinho',
                'birthdate' => '2022-10-10',
                'parent_id' => 3,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 3,
            ],
            [
                'id_student' => 21,
                'name' => 'Lady Franjinha Almeida',
                'birthdate' => '2021-06-22',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 3,
            ],
            [
                'id_student' => 22,
                'name' => 'Senhor Miadinho',
                'birthdate' => '2020-08-01',
                'parent_id' => 1,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 3,
            ],
            [
                'id_student' => 23,
                'name' => 'Petúnia Balinha de Morango',
                'birthdate' => '2013-11-18',
                'parent_id' => 2,
                'created_at' => Carbon::parse('2024-12-10 17:03:29'),
                'updated_at' => null,
                'id_class' => 3,
            ],
            [
                'id_student' => 24,
                'name' => 'JJ',
                'birthdate' => '2008-10-25',
                'parent_id' => 4,
                'created_at' => Carbon::parse('2024-12-10 22:29:29'),
                'updated_at' => Carbon::parse('2024-12-10 22:29:29'),
                'id_class' => 1,
            ],
        ]);
    }
}
